name = "SysBioModels"
uuid = "e071f4b8-ddce-11ed-170e-0fd2ebd54ecd"
authors = ["Max de Rooij <m.d.rooij@tue.nl>", "Balazs Erdos <balazs.erdos@maastrichtuniversity.nl>"]
version = "1.0.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
