name = "EdesVersions"
uuid = "3685e40e-ddcf-11ed-2336-ed99e3abb085"
authors = ["Max de Rooij <m.d.rooij@tue.nl>", "Balazs Erdos <balazs.erdos@maastrichtuniversity.nl>"]
version = "1.0.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SysBioModels = "e071f4b8-ddce-11ed-170e-0fd2ebd54ecd"
